version: '3.1'

services:
  database:
    image: postgres
    container_name: lic-database
    ports:
      - "5435:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres